Repository RobustIntelligence/ri-public-examples, pull requests merged in 2022-06, with the labels that each got.

#8 add stress config for fraud
  tabular/fraud/stress_test_config.json
Labels: size/S

#9 Update fraud.zip file
  tabular/fraud.zip
Labels: size/XS

#7 Resolves bug when timestamp part of stress test eval set
  tabular/fraud.zip
  tabular/fraud/fraud_eval.csv
Labels: size/XXL

#10 add OT stress test configs to rest of examples
  nlp/classification/arxiv/configs/stress_test_config.json
  nlp/classification/sentiment_analysis.zip
  nlp/classification/sentiment_analysis/configs/stress_test_config.json
  tabular/fraud.zip
  tabular/fraud/configs/stress_test_config.json
  tabular/fraud/stress_test_config.json
  tabular/income.zip
  tabular/income/configs/stress_test_config.json
  tabular/nyc_tlc/configs/stress_test_config.json
Labels: size/M

#14 REFACTOR (tabular/fraud): use pointers + download script for large files (models and data)
  tabular/fraud/Models/fraud_model.catb
  tabular/fraud/Models/fraud_model.py
  tabular/fraud/configs/stress_test_config.json
  tabular/fraud/data_urls.csv
  tabular/fraud/fraud_eval.csv
  tabular/fraud/fraud_incremental.csv
  tabular/fraud/fraud_ref.csv
  tabular/fraud/model_urls.csv
Labels: size/XXL

#13 REFACTOR (tabular/income): use pointers + download script for large files (models and data)
  tabular/income.zip
  tabular/income/configs/stress_test_config.json
  tabular/income/data_urls.csv
  tabular/income/eval_with_preds.csv
  tabular/income/model/cat_features.pkl
  tabular/income/model/cont_features.pkl
  tabular/income/model/model.catb
  tabular/income/model/model.py
  tabular/income/model_urls.csv
  tabular/income/ref_with_preds.csv
Labels: size/XXL

#16 Cleanup: fix NYC config + remove zip
  tabular/fraud.zip
  tabular/nyc_tlc/configs/stress_test_config.json
Labels: size/XS

#15 REFACTOR (update readme)
  README.md
Labels: size/S

#18 Adding new links to fraud dataset
  tabular/fraud/data_urls.csv
  tabular/fraud/model_urls.csv
Labels: size/XS

#20 update nlp config
  nlp/classification/arxiv/configs/stress_test_config.json
Labels: size/XS

#19 add urls+configs for awa dataset
  README.md
  download_files.py
  images/classification/awa2/configs/stress_test_config.json
  images/classification/awa2/data_urls.csv
  images/classification/awa2/fast_test_config.json
  images/classification/awa2/model_urls.csv
Labels: size/M

#21 update awa2 urls
  images/classification/awa2/data_urls.csv
Labels: size/XS

#22 fix json urls in awa2 dataset
  images/classification/awa2/data_urls.csv
Labels: size/XS

#24 add load path to image config
  images/classification/awa2/configs/stress_test_config.json
Labels: size/XS

#23 Uploaded information for Ranking Demo
  tabular/ranking/configs/stress_test_config.json
  tabular/ranking/data_urls.csv
Labels: size/S

#25 add back old fraud zip folder
  tabular/fraud.zip
Labels: size/XS

#26 Create model_urls.csv
  tabular/ranking/model_urls.csv
Labels: size/XS

#27 Create setup.py for ri-public-examples
  README.md
  download_files.py
  ri_public_examples/__init__.py
  ri_public_examples/download_files.py
  setup.py
Labels: size/L

#28 rm print in download_files
  ri_public_examples/download_files.py
Labels: size/XS

#29 create dirs if don't exist
  ri_public_examples/download_files.py
Labels: size/XS

#32 add custom metrics nyc
  tabular/nyc_tlc/model_urls.csv
Labels: size/XS

#33 add model.py file to nyc_tlc project directory
  tabular/nyc_tlc/model_urls.csv
Labels: size/XS
